// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1common "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

type HostnameTLSSettingInitParameters struct {

	// (String) The hostname for which the tls settings are set.
	// The hostname for which the tls settings are set.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	// The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (Dynamic) The tls setting value.
	// The tls setting value.
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1common.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1common.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type HostnameTLSSettingObservation struct {

	// (String) This is the time the tls setting was originally created for this hostname.
	// This is the time the tls setting was originally created for this hostname.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The hostname for which the tls settings are set.
	// The hostname for which the tls settings are set.
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	// The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (String) Deployment status for the given tls setting.
	// Deployment status for the given tls setting.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) This is the time the tls setting was updated.
	// This is the time the tls setting was updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (Dynamic) The tls setting value.
	// The tls setting value.
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type HostnameTLSSettingParameters struct {

	// (String) The hostname for which the tls settings are set.
	// The hostname for which the tls settings are set.
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	// The TLS Setting name.
	// Available values: "ciphers", "min_tls_version", "http2".
	// +kubebuilder:validation:Optional
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (Dynamic) The tls setting value.
	// The tls setting value.
	// +kubebuilder:validation:Optional
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1common.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1common.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// HostnameTLSSettingSpec defines the desired state of HostnameTLSSetting
type HostnameTLSSettingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            HostnameTLSSettingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HostnameTLSSettingInitParameters `json:"initProvider,omitempty"`
}

// HostnameTLSSettingStatus defines the observed state of HostnameTLSSetting.
type HostnameTLSSettingStatus struct {
	v1common.ResourceStatus `json:",inline"`
	AtProvider              HostnameTLSSettingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// HostnameTLSSetting is the Schema for the HostnameTLSSettings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type HostnameTLSSetting struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostname) || (has(self.initProvider) && has(self.initProvider.hostname))",message="spec.forProvider.hostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settingId) || (has(self.initProvider) && has(self.initProvider.settingId))",message="spec.forProvider.settingId is a required parameter"
	Spec   HostnameTLSSettingSpec   `json:"spec"`
	Status HostnameTLSSettingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HostnameTLSSettingList contains a list of HostnameTLSSettings
type HostnameTLSSettingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HostnameTLSSetting `json:"items"`
}

// Repository type metadata.
var (
	HostnameTLSSetting_Kind             = "HostnameTLSSetting"
	HostnameTLSSetting_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: HostnameTLSSetting_Kind}.String()
	HostnameTLSSetting_KindAPIVersion   = HostnameTLSSetting_Kind + "." + CRDGroupVersion.String()
	HostnameTLSSetting_GroupVersionKind = CRDGroupVersion.WithKind(HostnameTLSSetting_Kind)
)

func init() {
	SchemeBuilder.Register(&HostnameTLSSetting{}, &HostnameTLSSettingList{})
}
