// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1common "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
)

type ZoneSettingInitParameters struct {

	// recommender enrollment setting.
	// ssl-recommender enrollment setting.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Setting name
	// Setting name
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (Dynamic) Current value of the zone setting.
	// Current value of the zone setting.
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier
	// Identifier
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1common.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1common.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type ZoneSettingObservation struct {

	// (Boolean) Whether or not this setting can be modified for this zone (based on your Cloudflare plan level).
	// Whether or not this setting can be modified for this zone (based on your Cloudflare plan level).
	Editable *bool `json:"editable,omitempty" tf:"editable,omitempty"`

	// recommender enrollment setting.
	// ssl-recommender enrollment setting.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Setting name
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) last time this setting was modified.
	// last time this setting was modified.
	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	// (String) Setting name
	// Setting name
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (Number) Value of the zone setting.
	// Notes: The interval (in seconds) from when development mode expires (positive integer) or last expired (negative integer) for the domain. If development mode has never been enabled, this value is false.
	// Value of the zone setting.
	// Notes: The interval (in seconds) from when development mode expires (positive integer) or last expired (negative integer) for the domain. If development mode has never been enabled, this value is false.
	TimeRemaining *float64 `json:"timeRemaining,omitempty" tf:"time_remaining,omitempty"`

	// (Dynamic) Current value of the zone setting.
	// Current value of the zone setting.
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier
	// Identifier
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ZoneSettingParameters struct {

	// recommender enrollment setting.
	// ssl-recommender enrollment setting.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Setting name
	// Setting name
	// +kubebuilder:validation:Optional
	SettingID *string `json:"settingId,omitempty" tf:"setting_id,omitempty"`

	// (Dynamic) Current value of the zone setting.
	// Current value of the zone setting.
	// +kubebuilder:validation:Optional
	Value *v1.JSON `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier
	// Identifier
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1common.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1common.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// ZoneSettingSpec defines the desired state of ZoneSetting
type ZoneSettingSpec struct {
	v1common.ResourceSpec `json:",inline"`
	ForProvider           ZoneSettingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZoneSettingInitParameters `json:"initProvider,omitempty"`
}

// ZoneSettingStatus defines the observed state of ZoneSetting.
type ZoneSettingStatus struct {
	v1common.ResourceStatus `json:",inline"`
	AtProvider              ZoneSettingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZoneSetting is the Schema for the ZoneSettings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type ZoneSetting struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.settingId) || (has(self.initProvider) && has(self.initProvider.settingId))",message="spec.forProvider.settingId is a required parameter"
	Spec   ZoneSettingSpec   `json:"spec"`
	Status ZoneSettingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneSettingList contains a list of ZoneSettings
type ZoneSettingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZoneSetting `json:"items"`
}

// Repository type metadata.
var (
	ZoneSetting_Kind             = "ZoneSetting"
	ZoneSetting_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZoneSetting_Kind}.String()
	ZoneSetting_KindAPIVersion   = ZoneSetting_Kind + "." + CRDGroupVersion.String()
	ZoneSetting_GroupVersionKind = CRDGroupVersion.WithKind(ZoneSetting_Kind)
)

func init() {
	SchemeBuilder.Register(&ZoneSetting{}, &ZoneSettingList{})
}
